Repository WildCodeSchool-2023-09/JS-RemoteFR-SACOD-P2-Thousand-Sunny, pull requests merged in 2023-10, with the labels that each got.

#4 Initialisation de Tailwind
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/postcss.config.js
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: REVIEW REQUESTED

#5 1ère vr footer done
  backend/pnpm-lock.yaml
  backend/yarn.lock
  frontend/src/App.jsx
  frontend/src/components/Footer.jsx
  frontend/yarn.lock
Labels: REVIEWED

#6 Us 01 sprint 01
  frontend/public/.gitkeep
  frontend/src/App.jsx
  frontend/src/assets/excalibur.svg
  frontend/src/assets/favicon.svg
  frontend/src/assets/logo.svg
  frontend/src/components/Navbar.jsx
Labels: REVIEWED, CONFLICTS RESOLVED, CORRECTIONS DONE

#12 Home+Footer+Navbar
  frontend/src/App.jsx
  frontend/src/assets/Affiche-film.jpg
  frontend/src/assets/fonds.png
  frontend/src/components/Footer.jsx
  frontend/src/components/Home.jsx
  frontend/src/components/Navbar.jsx
Labels: REVIEWED

#11 Ajout de la config pour React Rooter
  frontend/src/App.jsx
  frontend/src/components/Counter.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/main.jsx
  frontend/src/pages/Home.jsx
Labels: CONFLICTS

#14 Ajouts des chemins React Routeur + Différente Pages
  frontend/src/App.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Home.jsx
  frontend/src/main.jsx
  frontend/src/pages/Contact.jsx
  frontend/src/pages/Error.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Quiz.jsx
Labels: REVIEWED

#15 responsive nav + links
  frontend/src/assets/excalibur.svg
  frontend/src/assets/logo-k.png
  frontend/src/components/Navbar.jsx
Labels: REVIEWED, CORRECTIONS DONE

#16 Ajout de la page Error + debug page Home
  frontend/src/assets/ca-fait-rien-cassez-vous.gif
  frontend/src/assets/javoue-suis-perdue.gif
  frontend/src/pages/Error.jsx
  frontend/src/pages/Home.jsx
Labels: REVIEWED
